### ISSUE TITLE
iOS problem reading protected-read keyfob

### ISSUE THREAD

**Issue by FaroukBoussarsar** [okadan/flutter-nfc-manager#105]
Reading a protected-read keyfob is working fine on android but when it generates an error even before accession ondiscover section
*ERROR* thrown:
> [CoreNFC] 00000002 81058c00 -[NFCMiFareTag queryNDEFStatusWithCompletionHandler:]:210  Error=Error Domain=NFCError Code=104 "Stack Error" UserInfo={NSLocalizedDescription=Stack Error, NSUnderlyingError=0x281050660 {Error Domain=nfcd Code=15 "Stack Error" UserInfo={NSLocalizedDescription=Stack Error}}}

**Comment by FaroukBoussarsar** [comment]
fixed the problem

**Comment by Andre-Coelhoo** [comment]
how?

**Comment by mahirandigital** [comment]
> fixed the problem

how you fix bro?
