### ISSUE TITLE
Error build for Iphone 14

### ISSUE THREAD

**Issue by redDwarf03** [okadan/flutter-nfc-manager#106]
Hello
when i want to build my project with iphone 14 which uses NFC_Manager, i obtain this error: 

```
Swift Compiler Error (Xcode): Stored properties cannot be marked potentially unavailable with '@available'
/flutter/.pub-cache/hosted/pub.dartlang.org/nfc_manager-3.1.1/ios/Classes/SwiftNfcManagerPlugin.swift:6:3
```

Any idea ?
Thx

**Comment by ibcoleman** [comment]
Exact same issue.

**Comment by artebiakin** [comment]
@redDwarf03 In my case, removing Podfile didn't help but updating it did.
So, try it:
`flutter clean`
`cd ios && rm -rf Pods/ .symlinks/ Podfile.lock`
`flutter pub get`
`pod install --repo-update` <- this command helped me

**Comment by okadan** [comment]
Fixed and published to pub.dev as v3.2.0.
