### ISSUE TITLE
instance.isAvailable returning false for iOS on a device I know NFC works on 

### ISSUE THREAD

**Issue by SRadfordM** [okadan/flutter-nfc-manager#109]
Working on a country specific version of an application at my company.  I ported over everything from one code base to another and made only minor changes for country specific code.  The NFC reader on this new application does work for Android, but does not work for iOS. I receive no errors...just need some help understanding what possibly could be missing. 

Within the NFC scanner widget, the log I get back in the database shows that isAvailable is returning false and it's not an error being thrown.  

![image](https://user-images.githubusercontent.com/79461502/193611632-a5e5caea-721e-4f06-9d33-95e403fa93eb.png)

I have the same version in pubspec.lock on both applications: 

![image](https://user-images.githubusercontent.com/79461502/193611945-5b08b965-d331-4a0b-a7ef-881ff928845e.png)

I have NFC enabled in the app identifier and provisioning profile: 

![image](https://user-images.githubusercontent.com/79461502/193612171-ceeb9e31-2d76-43be-ac29-8fa5b7af6d28.png)

![image](https://user-images.githubusercontent.com/79461502/193612287-679aec06-fa03-4d8b-8edf-16ce9b2ebed3.png)

I have the three steps for the entitlements and info.plist copied over from the application where it works.  

![image](https://user-images.githubusercontent.com/79461502/193612463-cbb7daf4-659e-4ea6-a8d3-1ecd39b17c1f.png)

![image](https://user-images.githubusercontent.com/79461502/193612648-f8f380be-c942-40f0-8bef-590d58c28f5c.png)

I tried to skip the isAvailable check and just start the session for more info and got: 

type: NfcErrorType.unknown 
details: null 
message: Session invalidated unexpectedly

Flutter info: 

![image](https://user-images.githubusercontent.com/79461502/193637943-f94aa01f-2791-4017-9f73-8592b2ac9d2b.png)

**Comment by THJLearn** [comment]
I have the same problem, my phone is iPhone8 Plus iOS15.4 system, see the status is off, what is the solution?

**Comment by mahirandigital** [comment]
> I ge

how you resolve?
