### ISSUE TITLE
No method to convert data to hex?

### ISSUE THREAD

**Issue by Tomacao** [okadan/flutter-nfc-manager#137]
I'm trying to convert the mifare identifier to hex number but i can't find the method to do it. Is it possible?

**Comment by janniklind** [comment]
You can map the identifier (Uint8List) to hex string using toRadixString already in dart core:

`final identifierHexString = identifierBytes.map((e) => e.toRadixString(16).padLeft(2, '0')).join('').toUpperCase();`
