### ISSUE TITLE
invalidateAfterFirstRead is not possible in current version

### ISSUE THREAD

**Issue by FTKhanFT** [okadan/flutter-nfc-manager#139]
Hi, do you have any plan to add invalidateAfterFirstRead feature on ios? What if we don't want to keep pooling after the first successful discovery of the tag?

Currently i'm working on a project where i want to read tag only once but in ios after successfull reading a tag it still shows the popup for reading. If i stop session by _instance.stopSession()_ method then start a new sessions it returns **SystemBusey** and if i stop that and restart the session it returns **userCanceled**

**Comment by okadan** [comment]
@FTKhanFT This may have been solved by #111 .
