### ISSUE TITLE
write lock

### ISSUE THREAD

**Issue by adham-ashraf77** [okadan/flutter-nfc-manager#14]
can i do unlock NFC card after i locked it and what password is given to card when it lock.

**Comment by okadan** [comment]
@adham-ashraf77 

Sorry, This project mainly focused on providing a platform channel to iOS/Android API.

Therefore, I don't think It's a good place to help with individual tag specifications.

Please consider referring to StackOverflow and so on.

**Comment by adham-ashraf77** [comment]
okay but can you tell me the password stored to NFC card when i lock it

**Comment by okadan** [comment]
@adham-ashraf77 

This plugin does not store password.
