### ISSUE TITLE
additionalData property of Ndef-Object is empty on iOS

### ISSUE THREAD

**Issue by philitell** [okadan/flutter-nfc-manager#147]
Reading a properly configured nfc-tag (with a NDEF-message) returns different results on android and iOS (testing for iOS 15.2 on an iPhone 8).
I am using ntag213-Tags with a valid NDEF-message.
When i create an Ndef-Object with this package the resulting object is incomplete on iOS (the object itself is not null).
`Ndef? ndefTag = Ndef.from(tag);`

The additionalData-map only contains values on android.
```
ndefTag.additionalData["type"] 
ndefTag.additionalData["identifier"]
```
On iOS this map is empty.

If this is the intended behaviour, how do i get the identifier from a Ndef-Tag?

**Comment by okadan** [comment]
@philitell That's the intended behavior. 

To get the identifier on iOS, you will need to use other classes such as MiFare/FeliCa/Iso15693/Iso7618.
