### ISSUE TITLE
App to send data from one phone to NFC device

### ISSUE THREAD

**Issue by mavbcn** [okadan/flutter-nfc-manager#15]
Hi,
I'd need to create an app to use NFC to receive and send data to a device.
I want to detect the device, read its ID , do a process in the app, and send a OK message to that device. Can I do it with this package with a flutter app? 
please let me know
thanks so much for your help

**Comment by okadan** [comment]
@mavbcn 

I don't know exactly what you want to do.

Please consider referring to API reference or StackOverflow for issues such as "How to"

**Comment by Srj-Love** [comment]
Hi @mavbcn , did you found any solution? My requirement is similar to you.
