### ISSUE TITLE
Is it possible to do get the UID from the Ndef tag?

### ISSUE THREAD

**Issue by firstmetcs** [okadan/flutter-nfc-manager#155]
The Ndef tag does not have the property `identifier`, while the original data `tag.data` has the property.

**Comment by okadan** [comment]
@firstmetcs To get the identifier, you have to use some other class.

**Comment by shehzadraheem** [comment]
> [@firstmetcs](https://github.com/firstmetcs) To get the identifier, you have to use some other class.

Can you please give let me know about the other classes?
