### ISSUE TITLE
iOS iso15693 - Issue with Present Password Command (0xB3)

### ISSUE THREAD

**Issue by SushantShidore-Copeland** [okadan/flutter-nfc-manager#198]
This is how I send the 'present password' command:

`Uint8List feedPassword = Uint8List.fromList([0x01, 0x55, 0xAA, 0x55, 0xAA, 0x9C, 0xDE, 0x2C, 0x74]);`
`int pwdCommandCode = 0xB3;`
`var requestFlagsForPwdAuth = <Iso15693RequestFlag>{};`
`requestFlagsForPwdAuth.add(Iso15693RequestFlag.highDataRate);`

`Uint8List? pwdResponse = await stTag?.customCommand(requestFlags: requestFlagsForPwdAuth, customCommandCode: pwdCommandCode, customRequestParameters: feedPassword);`

I've made sure that the password is correct such that when I forcefully feed a wrong password, a platform exception gets fired everytime. If the password is correct, an empty command response is received and there is no exception. The code follows through.

Now after the present password command, if I attempt normal read
`List<Uint8List>? readData = await stTag?.readMultipleBlocks(requestFlags: requestFlagsForRead, blockNumber: 4, numberOfBlocks: 1);`

, I always get this exception on the call to read command - 
PlatformException(invalid_parameter, Tag is not found, null, null)

I've tried using extendedReadSingleBlock / extendedReadMultipleBlocks, but have got the same results.

**Comment by SushantShidore-Copeland** [comment]
Nothing wrong with the command.
I had missed adding `await` on one of the method calls inside `onDiscovered`.
Apparently this affects only on the 'customCommand' API.

Marking this issues as Closed.

**Comment by nishidhmoon** [comment]
Can you please provide the code for setting a write restriction with a password? @sushant-shidore
