### ISSUE TITLE
Can You Add Password Feature

### ISSUE THREAD

**Issue by yunusemrecetin** [okadan/flutter-nfc-manager#20]
Hello, 

Can you add the password feature in this library? 'Cause I want to rewrite NFC tag with the password, the lock feature makes NFC unusable.

thanks

**Comment by okadan** [comment]
This library mainly focuses on the bridge to the Android/iOS API.
As far as I know, these password features are proprietary to the vendor and not part of the Android/iOS API.
Therefore, there is no plan for it.

However, you will be able to achieve these features by using the API that sends the vendor-specific-commands. (e.g. `transceive`, `sendMifareCommand`)
