### ISSUE TITLE
Exception: decodeObjectForKey: class "NFFieldNotification" not loaded or does not exist

### ISSUE THREAD

**Issue by 1993-tensa-g** [okadan/flutter-nfc-manager#3]
IOS version: 13.2.3

Error occurs after initiation of Read/ Write events on both devices.

> [xpc.exceptions] <NSXPCConnection:> connection to service on pid 85 named com.apple.nfcd.service.corenfc: Exception caught during decoding of received selector didDetectExternalReaderWithNotification:, dropping incoming message.

> Exception: Exception while decoding argument 0 (# 2 of invocation):
> Exception: decodeObjectForKey: class "NFFieldNotificationECP1_0" not loaded or does not exist

Note: Events are getting triggered, Ready To scan Popup is disappearing.

**Comment by okadan** [comment]
@1993-GB 

I think this is an issue related to iOS, not this plugin.

Anyway, I need more information.

- Provide your `flutter doctor -v`
- Make sure that you follow the setup instruction of `README.md`

**Comment by 1993-tensa-g** [comment]
@okadan 

I am running Example app as well.. it is giving same errors.

Here is Flutter doctor -v result

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G1012, locale en-JP)
    • Flutter version 1.9.1+hotfix.6 at /Users/XXX/Documents/flutter
    • Framework revision (10 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/~/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/~/java
    • Java version OpenJDK Runtime Environment ()
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/~/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/~/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone • XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX • ios • iOS 13.2.3

**Comment by okadan** [comment]
@1993-GB 

Thanks.

Are `Provisioning Profile` and `Runner.entitlements` appropriate?

**Comment by 1993-tensa-g** [comment]
@okadan 

Yes.. I have a new developer account and i have completed all steps in the Readme file.

**Comment by okadan** [comment]
@1993-GB 

Please check the result of `NfcManager.isAvailable(NfcSessionType.tag)`.

**Comment by 1993-tensa-g** [comment]
@okadan 

is there any minimum handset version requirement for iphone?

Which device are you testing on ..?

Because Apple Reference app is also not working [Apple Reference app](https://developer.apple.com/documentation/corenfc/building_an_nfc_tag-reader_app)

It is also exiting with the same error.

**Comment by okadan** [comment]
@1993-GB 

> is there any minimum handset version requirement for iphone?

To use `startTagSession`, iOS13 or later is required.

> Which device are you testing on ..?

iPhone7 / iOS13.2.3.

I still think this is an iOS layer issue, not a plugin issue.

Check `NfcManager.isAvailable` to make sure that your iOS setup is valid.

**Comment by 1993-tensa-g** [comment]
@okadan 

Both Tag and Ndef are returning True for isAvailable!!

**Comment by okadan** [comment]
@1993-GB 

Sorry, I have no ideas.

> Because Apple Reference app is also not working Apple Reference app

Does this mean that the same error occurs in a native iOS project?

In that case, it's not an issue with this plugin.

**Comment by 1993-tensa-g** [comment]
@okadan 

Yes !! it looks like so!
Sorry for the trouble caused...

**Comment by 1993-tensa-g** [comment]
@okadan 

Can we use this framework for communication between two iPhones?

**Comment by jams032** [comment]
@1993-tensa-g , I have the same question. But i think the answer is YES. Recently, we were capable of writing data in Android phone and read that from iOS app. The code was based on java and iOS project is based on swift. The sad part is, we still are not capable of writing data in iOS app, and then read from Android app as well. We are struggling on this.
