### ISSUE TITLE
nfc manager does not check NFC permission.

### ISSUE THREAD

**Issue by AkiraK8** [okadan/flutter-nfc-manager#32]
I found 2 issues about the nfc permission.

1. "request permission" is shown at second time, not at first time.
When startSession() is called 2 times, "request permission" is shown.

2. status of permission is not checked.
Even though a user denies the nfc permission, nfc_manager keeps to access to nfc.

using version nfc_manager: ^2.0.0+2

**Comment by magicmass** [comment]
Also have this issue. Sadly, I haven't found a solution either. Will be sure to post an update if anything changes.

**Comment by AcumenianDev** [comment]
Any updates on this issue?

**Comment by AkiraK8** [comment]
Sorry, I have nothing to update
