### ISSUE TITLE
Increase the session timeout (Scanning time) in iOS

### ISSUE THREAD

**Issue by ishwaryamamidi** [okadan/flutter-nfc-manager#35]
I'm using this plugin in my app. I have a scenario where I need to send multiple commands with binary data to my nfc tag (ISO 15693). Sending this data takes almost 40-45 seconds. Ideally, I want the 'Ready to scan' popup till all the data is sent to the charger. But it closes (with check tick mark) after around 30 secs and then I get an error '**[CoreNFC] 00000002 81002300 -[NFCTagReaderSession transceive:tagUpdate:error:]:710  Error Domain=NFCError Code=100 "Tag connection lost" UserInfo={NSLocalizedDescription=Tag connection lost}**'. 

Is there a way to increase the nfc scanning time (or exrend the nfc reader session)?

**Comment by okadan** [comment]
Apple doesn't  seem to provide an API to solve this.
