### ISSUE TITLE
how to convert function byte string to dart

### ISSUE THREAD

**Issue by sabardotnet** [okadan/flutter-nfc-manager#46]
public static final byte[] f1504a = {48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 65, 66, 67, 68, 69, 70};
    public static final byte[] bArr = {96, 50, (byte) 152, 96, (byte) 147, 80, (byte) 147, 18, 36, 17, 1, 32, (byte) 145, 17, 4, 84, 0, (byte) 145, 3, 1, 6, 0, 0, 0, 0, 0, 3, 116, 87, (byte) 175, 116, 7, (byte) 174, (byte) 206, (byte) 244, 15, (byte) 227, (byte) 162, 68, 9, (byte) 244, (byte) 236, 73, 59, 3, 84, 120, (byte) 132, (byte) 182, (byte) 174, (byte) 176, 80, (byte) 195, 0, 17, 1, 32, 3, (byte) 246, 61, 13, (byte) 255, (byte) 255, (byte) 144, 0};
*bArr is my result 2 layer transceive with nfc_manager

    public static String b(byte[] bArr, int i) {
        byte[] bArr2 = new byte[(i * 2)];
        int i2 = 0;
        int i3 = 0;
        for (byte b2 : bArr) {
            if (i2 >= i) {
                break;
            }
            i2++;
            int i4 = b2 & 255;
            int i5 = i3 + 1;
            byte[] bArr3 = f1504a;
            bArr2[i3] = bArr3[i4 >>> 4];
            i3 = i5 + 1;
            bArr2[i5] = bArr3[i4 & 15];
        }
        return new String(bArr2);
    }
b(bArr, 8);

I tested this with java and the result 6032986093509312 same with my nfc card number

how i make function like this in dart / flutter. thanks for answering

**Comment by okadan** [comment]
This issue is not related to this plugin.

Please see the `Uint8List` document or StackOverflow.
