### ISSUE TITLE
Feature Request: Password Protected Tags

### ISSUE THREAD

**Issue by JaffaKetchup** [okadan/flutter-nfc-manager#47]
Hello all,
I think a rather useful feature would be to be able to password protect new/existing tags or create read only tags. This is supported by some NDEF formatted cards and would allow these tags to be placed in public places, without making them vulnerable to sabotage or even accidental writing.
Password protected tags would require the password to be removed to make them writable (they'd always be readable). Read only tags would never be able to be written again.
Thanks, and I hope this idea does get implemented because it is a main idea of my app.

**Comment by JaffaKetchup** [comment]
Ok, so I've just downloaded the example app, and it looks like there is a permeant locking feature that works. Great!

Not so great when there is no warning that that's what it's going to do and there is no way to undo it. Please add a warning (fix the ListFooter widget), because now I have a locked tag with no data on it. I've opened an issue for this on the example repo: https://github.com/okadan/flutter-nfc-manager-app/issues/6.

But anyway, that's still extremely useful and good news for my app, as no other library seems to be able to do that. Is it possible to have password protected tags, because that is supported by some tags, and would be more useful, and undoable!?

**Comment by okadan** [comment]
Duplicate of #20
