### ISSUE TITLE
Can't get it to work on iOS

### ISSUE THREAD

**Issue by pauldev20** [okadan/flutter-nfc-manager#50]
For some reason if I try to use this plugin with an iPhone it won't work. Nothing happens if I use the example code and tap a empty NFC Tag on the back of the phone. I will only get this error: ```[CoreNFC] 00000002 81c8b4e0 -[NFCTagReaderSession beginSessionWithConfig:]:378  error:Error Domain=NFCError Code=203 "System resource unavailable" UserInfo={NSLocalizedDescription=System resource unavailable}, errorCode: 0xcb```

**Comment by okadan** [comment]
@pauldev20 

Please check https://github.com/okadan/flutter-nfc-manager/issues/38#issuecomment-773263413
