### ISSUE TITLE
Exception writing to read only tag.  Needs a better message in exception.

### ISSUE THREAD

**Issue by sgehrman** [okadan/flutter-nfc-manager#6]
I'm on Android, I try and write to a readonly tag, but I get back a blank PlatformException rather than a useful message like 'tag is readonly'.

Error comes from     final T typedResult = codec.decodeEnvelope(result);
Exception has occurred.
PlatformException (PlatformException(io_exception, null, null))

**Comment by okadan** [comment]
Hi @sgehrman .

First, It seems that the Android system does not provide any messages. 
(the `localizedDescription` property is `null`)

Second, I think that the plugin should not generate their own custom messages.

So, what the app developers can do is build their own error messages using properties such as `Ndef.isWritable`.
