### ISSUE TITLE
How to prevent using device default reader

### ISSUE THREAD

**Issue by betrri** [okadan/flutter-nfc-manager#79]
Hello! 

I have this code to get the identifier of the tag when reading. 

```
void _tagRead() {
    NfcManager.instance.startSession(onDiscovered: (NfcTag tag) async {
      Ndef? ndef = Ndef.from(tag);
      result.value = tag.data;
      print('Tag read: ');
      final String identifier = tag.data['ndef']['identifier']
          .map((e) => e.toRadixString(16).padLeft(2, '0'))
          .join('');
      print(identifier);
      NfcManager.instance.stopSession();
    });
  }
```

The problem is that when successfully reading the tag, the device default reader pops and removing focus from the application. How this behaviour is prevented.

edit: The running device is OnePlus 7 Pro

**Comment by okadan** [comment]
@betrri 

Currently, there is no way to disable the Android default tag detection from this plugin.

See below for workarounds:
https://github.com/okadan/nfc-manager/blob/master/android/app/src/main/kotlin/com/naokiokada/nfcmanager/MainActivity.kt
