### ISSUE TITLE
Crash reading Mifare Classic emulation card.

### ISSUE THREAD

**Issue by dididudikov** [okadan/flutter-nfc-manager#81]
Some android smartphone will crash reading Mifare classic emulation card. Card that contain Isodep and Mifare Classic tech in single card. I have to patch the code to resolve this problem. it will be great if there is option weather enable or disable reading emulation Mifare classic in the parameter.

Fatal Exception: java.lang.RuntimeException: Tag incorrectly enumerated as MIFARE Classic, SAK = 32
       at android.nfc.tech.MifareClassic.<init>(MifareClassic.java:200)
       at android.nfc.tech.MifareClassic.get(MifareClassic.java:138)

**Comment by okadan** [comment]
Duplicate of #51
