### ISSUE TITLE
Wrong output from ndef message.

### ISSUE THREAD

**Issue by vadrian89** [okadan/flutter-nfc-manager#92]
Hello, when trying to retrieve the content I get the string with other chars appended.

The content from the tag is "yoooo" as seen in the following screenshot:
![5de0a7b4-2afb-465c-bb8c-ce4e6a48d203](https://user-images.githubusercontent.com/8177798/165319057-371d3e53-1427-47cb-8c35-fef42ca49020.jpeg)

The code
```
final message = ndef.cachedMessage;
final payload = message?.records[0].payload ?? const Iterable<int>.empty();
final payloadStr = String.fromCharCodes(payload);
print("payloadStr $payloadStr");
```
The printed output in the debug console: 
![image](https://user-images.githubusercontent.com/8177798/165319395-bf6afaf1-bc0b-4538-b23a-01966179122c.png)

I have also tried:
```
final payload = message?.records[0].payload ?? <int>[];
final payloadStr = Utf8Decoder().convert(payload);

```
But it has the same result.

**Comment by philitell** [comment]
There are additional bytes in front of the payload (this is correct) - see this example how to properly read your payload by skipping the first bytes: https://github.com/Dev-Owl/flutter_nfc_example/blob/main/lib/main.dart#L175
